### ISSUE TITLE
Get Workflows working

### ISSUE THREAD

**Issue by torbencarstens** [torbencarstens/dhall-circleci#1]
I'm currently stuck on the implementation of this part of a workflow:

```yml
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run
      - pdoc
      - build:
          requires:
            - run
          filters:
            branches:
              only:
                - develop
                - master
```

I can't get the Union of jobs working correctly (that is, dynamic keys in the job list).

---

First try:
```dhall
[
        {
            mapKey = "version"
            , mapValue = < Version = 2 | Workflow : { jobs : List < Name : Text | Job : { mapKey: Text, mapValue : { requires : Optional (List Text), filters : Optional { branches : { only : Optional (List Text) } } } } > } >
        }
        ,{
            mapKey = "build_and_deploy"
            , mapValue =
                < Version : Natural | Workflow = { jobs = [
                        < Name = "job" | Job : { mapKey : Text, mapValue : { requires : Optional (List Text), filters : Optional { branches : { only : Optional (List Text) } } } } >
                        , (keyValue "build" { requires = (Some ["asd"]), filters = None { branches : { only : Optional (List Text) } } })
                    ]
                } >
        }]
```

-> 
```yml
workflows:
  build_and_deploy:
    jobs:
    - job
    - mapKey: build
      mapValue:
        requires:
        - asd
  version: 2
```

Not sure why `mapKey` and `mapValue` aren't replaced correctly... seems like a deep nesting issue.

**Comment by torbencarstens** [comment]
```dhall
workflows =
        {jobs = [
        < A = {
            nesting  = Nesting.Nested "run"
            , field = "job"
            , contents = Example.Right "contents"
        } | B : { mapKey : Text, mapValue : Text} >,
        < A : { nesting : Nesting, field : Text, contents : Example } | B = {
            mapKey = "job",
            mapValue = "test"
        } >
        ]}
```
->
```yml
workflows:
  jobs:
  - run: contents
    job: Right
  - mapKey: job
    mapValue: test
```

Same issue (`mapKey` and `mapValue`) stay the same.
